repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks detect --redact --verbose --no-git --source=.
        language: system
        pass_filenames: false
        stages: [pre-commit, manual]
        always_run: true
      - id: markdownlint
        name: Lint Markdown files
        description: Check and auto-fix Markdown style issues
        entry: markdownlint-cli2 --fix
        language: system
        types: [markdown]
        pass_filenames: true
